name: Project Rules Check

on: [pull_request]

jobs:
  rules_check:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Node Dependencies
        run: npm ci
        env:
          CI: TRUE
      - name: Check React Project
        uses: VictorDanilov/react-project-checker-action@v0.0.2-alpha
